# Generated by Django 2.2.2 on 2019-06-07 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder_project', '0006_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updates', to='crowdfunder_project.Project'),
        ),
    ]
