# Generated by Django 2.2.2 on 2019-06-07 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder_project', '0007_auto_20190607_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='crowdfunder_project.Project'),
        ),
    ]
