# Generated by Django 2.2.2 on 2019-06-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder_project', '0008_auto_20190607_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
