# Generated by Django 2.2.2 on 2019-06-10 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder_project', '0009_update_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_dtime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_dtime',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
