# Generated by Django 2.2.2 on 2019-06-10 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder_project', '0010_auto_20190610_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_dtime',
            field=models.DateField(default=datetime.datetime(2019, 6, 10, 16, 46, 53, 665548)),
        ),
    ]
