# Generated by Django 2.2.2 on 2019-06-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder_project', '0011_auto_20190610_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_dtime',
            field=models.DateField(),
        ),
    ]
